import type { FieldSpec } from "@/shared/forms";
import type { SettingKey } from "./schemas";

export const settingMeta: Record<SettingKey, { title: string; description: string; fields: FieldSpec[] }> = {
  brand: {
    title: "Brand",
    description: "Name, logo and colors. Changing the name updates the website, emails, invoices, SMS, PWA manifest and favicon instantly.",
    fields: [
      { name: "name", label: "Brand name", required: true, help: "Shown everywhere: header, footer, titles, emails, invoices." },
      { name: "legalName", label: "Display legal name (footer)", help: "Optional, e.g. “RoadSaathi Mobility Pvt. Ltd.”" },
      { name: "tagline", label: "Tagline", type: "localized" },
      { name: "description", label: "Short description (SEO)", type: "localizedTextarea", rows: 3 },
      { name: "logoUrl", label: "Logo image URL", type: "url", help: "Optional. Square PNG/SVG. Leave empty to use the auto-generated mark." },
      { name: "primaryColor", label: "Primary color", type: "color", section: "Colors" },
      { name: "inkColor", label: "Ink / charcoal color", type: "color" },
      { name: "facebook", label: "Facebook URL", type: "url", section: "Social" },
      { name: "instagram", label: "Instagram URL", type: "url" },
      { name: "x", label: "X (Twitter) URL", type: "url" },
      { name: "youtube", label: "YouTube URL", type: "url" },
      { name: "linkedin", label: "LinkedIn URL", type: "url" },
    ],
  },
  contact: {
    title: "Contact & address",
    description: "Phone numbers, emails and office address shown on the site, in emails and on invoices.",
    fields: [
      { name: "phone", label: "Main phone", type: "tel" },
      { name: "emergencyPhone", label: "Emergency / 24x7 phone", type: "tel", help: "Used for every “Call now” button." },
      { name: "whatsapp", label: "WhatsApp number (digits only, with country code)", help: "e.g. 919000000000" },
      { name: "email", label: "General email", type: "email" },
      { name: "supportEmail", label: "Support email", type: "email" },
      { name: "partnersEmail", label: "Partners email", type: "email" },
      { name: "hours", label: "Operating hours" },
      { name: "addressLine", label: "Address line", section: "Office address", full: true },
      { name: "city", label: "City" },
      { name: "state", label: "State" },
      { name: "pincode", label: "PIN code" },
      { name: "lat", label: "Latitude", type: "number", step: "any" },
      { name: "lng", label: "Longitude", type: "number", step: "any" },
    ],
  },
  business: {
    title: "Business, GST & invoicing",
    description: "Legal entity and GST details used on tax invoices. Verify SAC code and rate with your chartered accountant.",
    fields: [
      { name: "legalName", label: "Legal entity name", full: true },
      { name: "gstin", label: "GSTIN" },
      { name: "pan", label: "PAN" },
      { name: "cin", label: "CIN (optional)" },
      { name: "stateName", label: "State (place of supply)" },
      { name: "stateCode", label: "GST state code", help: "Delhi = 07" },
      { name: "sacCode", label: "SAC code" },
      { name: "gstRatePct", label: "GST rate (%)", type: "number", step: "0.01" },
      { name: "invoicePrefix", label: "Invoice number prefix", help: "Invoices look like RS/2026-27/000001" },
      { name: "bookingPrefix", label: "Booking code prefix", help: "Booking codes look like RS-7K3M9Q2A" },
      { name: "invoiceFooter", label: "Invoice footer note", type: "textarea", full: true, rows: 2 },
    ],
  },
  pricing: {
    title: "Pricing rules",
    description: "Global rules applied on top of the per-vehicle rate cards (Admin → Rate cards).",
    fields: [
      { name: "nightStartHour", label: "Night surcharge starts (hour, 0-23)", type: "number" },
      { name: "nightEndHour", label: "Night surcharge ends (hour, 0-23)", type: "number" },
      { name: "nightMultiplier", label: "Night multiplier", type: "number", step: "0.01", help: "1.25 = +25%" },
      { name: "surgeMultiplier", label: "Surge / peak multiplier", type: "number", step: "0.01", help: "Set above 1 during heavy demand, 1 = off." },
      { name: "freeWaitingMinutes", label: "Free waiting minutes", type: "number" },
      { name: "cancellationFeeRupees", label: "Cancellation fee after driver assigned (₹)", type: "number" },
      { name: "platformCommissionPct", label: "Default platform commission (%)", type: "number", step: "0.1", help: "Can be overridden per provider." },
      { name: "roundToRupee", label: "Round fares to whole rupees", type: "checkbox" },
    ],
  },
  dispatch: {
    title: "Dispatch",
    description: "How the system finds and offers jobs to drivers.",
    fields: [
      { name: "searchRadiusKm", label: "Search radius (km)", type: "number" },
      { name: "offersPerRound", label: "Drivers offered per round", type: "number" },
      { name: "offerTimeoutSec", label: "Offer timeout (seconds)", type: "number" },
      { name: "maxRounds", label: "Max rounds before manual dispatch", type: "number" },
      { name: "driverFreshnessMin", label: "Driver location freshness (minutes)", type: "number", help: "Drivers not seen within this window are skipped." },
      { name: "allowScheduling", label: "Allow scheduled bookings", type: "checkbox" },
    ],
  },
  payments: {
    title: "Payments",
    description: "Razorpay is built in. Keep it on “coming soon” until your Razorpay account and RAZORPAY_* env keys are ready.",
    fields: [
      { name: "cashEnabled", label: "Pay after service (cash / UPI to driver)", type: "checkbox" },
      {
        name: "razorpayMode",
        label: "Razorpay online payments",
        type: "select",
        options: [
          { value: "coming_soon", label: "Coming soon (visible, disabled)" },
          { value: "test", label: "Test mode (needs test keys)" },
          { value: "live", label: "Live (needs live keys)" },
        ],
      },
    ],
  },
  maps: {
    title: "Maps",
    description: "OpenStreetMap is the default. Switch to Google Maps by choosing it here and setting GOOGLE_MAPS_API_KEY.",
    fields: [
      {
        name: "provider",
        label: "Map / geocoding provider",
        type: "select",
        options: [
          { value: "env", label: "Use MAP_PROVIDER from environment" },
          { value: "osm", label: "OpenStreetMap (Nominatim + OSRM)" },
          { value: "google", label: "Google Maps" },
        ],
      },
      { name: "tileUrl", label: "Map tile URL", full: true, help: "Use your own tile provider for production traffic." },
      { name: "centerLat", label: "Default center latitude", type: "number", step: "any" },
      { name: "centerLng", label: "Default center longitude", type: "number", step: "any" },
      { name: "zoom", label: "Default zoom", type: "number" },
    ],
  },
  notifications: {
    title: "Notifications",
    description: "Who gets emailed / texted. Provider credentials live in environment variables.",
    fields: [
      { name: "fromName", label: "Email sender name", help: "Defaults to the brand name." },
      { name: "fromEmail", label: "Email sender address", type: "email", help: "Defaults to EMAIL_FROM or the general email." },
      { name: "adminAlertEmail", label: "Ops alert email", type: "email", help: "Gets new booking / partner application alerts." },
      { name: "emailCustomers", label: "Email customers", type: "checkbox", section: "Channels" },
      { name: "emailDrivers", label: "Email drivers", type: "checkbox" },
      { name: "emailCompanies", label: "Email partner companies", type: "checkbox" },
      { name: "smsCustomers", label: "SMS customers", type: "checkbox" },
      { name: "smsDrivers", label: "SMS drivers", type: "checkbox" },
    ],
  },
  seo: {
    title: "SEO & analytics",
    description: "Search defaults and analytics.",
    fields: [
      { name: "titleSuffix", label: "Page title suffix", help: "Defaults to “| Brand name”." },
      { name: "keywords", label: "Default keywords", type: "textarea", full: true, rows: 3 },
      { name: "googleAnalyticsId", label: "Google Analytics ID (G-XXXX)" },
    ],
  },
};
